<?php

/***********************************************************************
 *
 * Ting - PHP Datamapper
 * ==========================================
 *
 * Copyright (C) 2026 Xavier Leune
 *
 ***********************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License.
 *
 **********************************************************************/

namespace tests\fixtures\model;

use CCMBenchmark\Ting\Entity\NotifyProperty;
use CCMBenchmark\Ting\Entity\NotifyPropertyInterface;
use tests\fixtures\ValueObject\AccountId;

/**
 * An entity whose autoincrement primary key is a value object, with a serializer of its own (mutable): its setter
 * also takes the raw id generated by the database
 */
class Account implements NotifyPropertyInterface
{
    use NotifyProperty;

    protected ?AccountId $id = null;
    protected ?string $name = null;

    public function getId(): ?AccountId
    {
        return $this->id;
    }

    public function setId(int|AccountId|null $id): void
    {
        $id = \is_int($id) ? new AccountId($id) : $id;
        $this->propertyChanged('id', $this->id, $id);
        $this->id = $id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): void
    {
        $this->propertyChanged('name', $this->name, $name);
        $this->name = $name;
    }
}
